### ISSUE TITLE
Option to ignore certificate validation

### ISSUE THREAD

**Issue by FichteFoll** [IGS/hmp_client#25]
One manifest file I tried to fetch using portal_client has HTTPS urls that point to a host whose TLS certificate has expired a month ago. Disabling validation is obviously a security risk, but would it be feasible to add this option?

However, ignoring the warning in FireFox and trying to access the url directly also yields a 403 Forbidden and it does not appear that portal_client is transmitting any sort of authentication, so it seems likely that this wouldn't help either.

https://github.com/IGS/portal_client/blob/24a1eb00b468d4688a3588231701ca7753490b39/lib/portal_http.py#L83-L90

**Comment by victor73** [comment]
Thank you for reporting the issue an expired certificate. We believe we have addressed that problem. However, we do not plan to make an alteration to the portal client to relax the validity of the certificate used to encrypt connections at this time.

**Comment by FichteFoll** [comment]
That's perfectly fine with me if the certificate is valid again. I wasn't sure where to report that since I was only helping someone else with getting `portal_client` to run and had no idea what the response time would be either.
