### ISSUE TITLE
HMP download URL not accessible

### ISSUE THREAD

**Issue by scs9** [IGS/hmp_client#28]
I'm having problems downloading fastq files from HMP. All files failed to be retrieved. I also tried copying and pasting the URLs into a couple of different browsers, but I got a Forbidden webpage saying I don't have permission despite all of the files being open access. 

Example manifest is attached:
[hmp_manifest_694398025.txt](https://github.com/user-attachments/files/16472855/hmp_manifest_694398025.txt)

Code:
`portal_client --manifest /work/normanlab/cdc_project_new_mapping/HMP_samples/hmp_manifest_694398025.tsv`

Output:
```
Not all files (total of 142) were downloaded successfully. Number of failures:
0 -- no valid URL in the manifest file
142 -- URL is present in manifest, but not accessible at the location specified
0 -- MD5 checksum failed for file (file is corrupted or the wrong MD5 is associated)
```

In an effort to fix the issue myself I tried to create a login on iHMP so I could add a username to the code and also got an error webpage: "This page isn’t workinghmpdacc.org is currently unable to handle this request. HTTP ERROR 500." Is there some sort of workaround that I'm not aware of? Any help is appreciated, thanks.

**Comment by victor73** [comment]
The HMP and IHMP websites, including the data portal, are retired as these projects have completed their funding periods. The data generated by these projects can be downloaded from the s3://hmpdacc AWS S3 bucket.
